name: Run Selenium Script

on:
  workflow_dispatch:
#on: [push]
#on:
#  schedule:
#    - cron: '0 23 * * *'   # KST 08:00
#    - cron: '0 2 * * *'    # KST 11:00
#    - cron: '0 5 * * *'    # KST 14:00
#    - cron: '0 8 * * *'    # KST 17:00
#    - cron: '0 11 * * *'   # KST 20:00
#    - cron: '0 14 * * *'   # KST 23:00

jobs:
  selenium-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python abc-bot.py
